name = "BirthDeathProcess"
uuid = "e072b36e-a5be-4874-a20d-e1d44194e9ec"
authors = ["Jose Manuel de Frutos"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
DifferentialEquations = "7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
